import * as stylex from "@stylexjs/stylex";
import { colorVars, radiusVars } from "@astryxdesign/core/theme/tokens.stylex";

export const styles = stylex.create({
  layout: { display: "grid", gridTemplateColumns: { default: "300px minmax(0, 1fr)", "@media (max-width: 700px)": "minmax(0, 1fr)" }, height: { default: "min(690px, calc(100dvh - 32px))", "@media (max-width: 700px)": "calc(100dvh - 32px)" }, overflow: "hidden", color: colorVars["--color-text-primary"] },
  story: { display: { default: "flex", "@media (max-width: 700px)": "none" }, flexDirection: "column", justifyContent: "space-between", padding: "32px", backgroundColor: "#173d34", color: "#f5f7e9", position: "relative", overflow: "hidden" },
  brand: { display: "flex", alignItems: "center", gap: "10px", fontSize: "19px", letterSpacing: "-0.5px" },
  local: { display: "block", letterSpacing: "3px", fontSize: "9px", color: "#bfd7c0", marginTop: "3px" },
  storyContent: { marginTop: "30px" },
  eyebrow: { fontSize: "10px", textTransform: "uppercase", letterSpacing: "2px", color: "#b5ceac", fontWeight: 600 },
  storyTitle: { color: "#f5f7e9", fontSize: "36px", lineHeight: 1.16, letterSpacing: "-1.2px", margin: "16px 0" },
  storyText: { fontSize: "14px", lineHeight: 1.7, color: "#cedbcf", margin: 0 },
  trust: { display: "flex", gap: "9px", alignItems: "center", fontSize: "11px", lineHeight: 1.5, color: "#bfd7c0" },
  illustration: { position: "relative", height: "205px", marginTop: "28px" },
  orbit: { position: "absolute", border: "1px solid #ffffff20", borderRadius: "50%", width: "220px", height: "220px", top: "-10px", left: "8px" },
  paper: { position: "absolute", width: "178px", height: "140px", backgroundColor: "#eef2db", borderRadius: "16px", top: "34px", left: "12px", padding: "20px", color: "#3c5b42", transform: "rotate(-7deg)", boxShadow: "0 16px 32px #071d2540" },
  paperBack: { top: "17px", left: "43px", backgroundColor: "#81a58c", transform: "rotate(9deg)" },
  artLine: { height: "6px", width: "70px", backgroundColor: "#b4c4a5", borderRadius: "4px", marginTop: "10px" },
  artBars: { display: "flex", alignItems: "end", gap: "7px", height: "40px", marginTop: "8px" },
  bar: (height: number) => ({ width: "21px", height, backgroundColor: "#799c6a", borderRadius: "4px" }),
  seal: { position: "absolute", bottom: "23px", right: "1px", borderRadius: "50%", width: "52px", height: "52px", display: "grid", placeItems: "center", color: "#173d34", backgroundColor: "#dfebb1", border: "5px solid #173d34" },
  main: { display: "flex", flexDirection: "column", minWidth: 0, minHeight: 0, backgroundColor: colorVars["--color-background-card"] },
  top: { display: "flex", alignItems: "center", justifyContent: "space-between", gap: "8px", padding: { default: "20px 32px 12px", "@media (max-width: 500px)": "12px 16px 8px" } },
  counter: { color: colorVars["--color-text-secondary"], fontSize: "11px", textTransform: "uppercase", letterSpacing: "1.2px", fontWeight: 600 },
  progress: { display: "flex", listStyle: "none", margin: 0, padding: { default: "8px 32px 20px", "@media (max-width: 500px)": "8px 16px 16px" }, gap: "8px", borderBottom: `1px solid ${colorVars["--color-border"]}` },
  progressItem: { flex: 1, display: "flex", alignItems: "center", gap: "6px", minWidth: 0, color: colorVars["--color-text-secondary"] },
  progressActive: { color: colorVars["--color-text-primary"] },
  dot: { display: "grid", placeItems: "center", flexShrink: 0, borderRadius: "50%", width: "22px", height: "22px", fontSize: "10px", border: `1px solid ${colorVars["--color-border"]}`, backgroundColor: colorVars["--color-background-card"] },
  dotActive: { borderColor: colorVars["--color-accent"], backgroundColor: `color-mix(in srgb, ${colorVars["--color-accent"]} 18%, ${colorVars["--color-background-card"]})`, fontWeight: 700 },
  dotDone: { backgroundColor: `color-mix(in srgb, ${colorVars["--color-accent"]} 12%, ${colorVars["--color-background-card"]})`, color: colorVars["--color-accent"] },
  stepLabel: { display: { default: "inline", "@media (max-width: 500px)": "none" }, fontSize: "10px", fontWeight: 600 },
  body: { flex: 1, minHeight: 0, overflowY: "auto", padding: { default: "26px 32px", "@media (max-width: 500px)": "20px 16px" }, overscrollBehavior: "contain" },
  stepIcon: { display: "grid", placeItems: "center", width: "48px", height: "48px", borderRadius: "15px", marginBottom: "18px", backgroundColor: `color-mix(in srgb, ${colorVars["--color-accent"]} 12%, ${colorVars["--color-background-card"]})`, color: colorVars["--color-accent"] },
  title: { fontSize: { default: "29px", "@media (max-width: 500px)": "25px" }, lineHeight: 1.2, letterSpacing: "-0.9px", margin: "0 0 10px", outline: "none", maxWidth: "420px" },
  description: { color: colorVars["--color-text-secondary"], fontSize: "14px", lineHeight: 1.65, margin: "0 0 24px" },
  benefits: { display: "grid", gap: "16px", marginBottom: "24px" },
  benefit: { display: "flex", gap: "12px", alignItems: "start", fontSize: "13px" },
  benefitIcon: { display: "grid", placeItems: "center", flexShrink: 0, width: "36px", height: "36px", borderRadius: "10px", backgroundColor: `color-mix(in srgb, ${colorVars["--color-accent"]} 8%, ${colorVars["--color-background-card"]})`, color: colorVars["--color-accent"] },
  small: { display: "block", margin: "5px 0 0", fontSize: "12px", lineHeight: 1.55, color: colorVars["--color-text-secondary"] },
  demo: { display: "flex", flexWrap: "wrap", alignItems: "center", gap: "14px", justifyContent: "space-between", padding: "16px", border: `1px solid ${colorVars["--color-border"]}`, borderRadius: radiusVars["--radius-inner"], fontSize: "12px" },
  fields: { display: "grid", gap: "18px" },
  fieldPair: { display: "grid", gridTemplateColumns: { default: "1fr 1fr", "@media (max-width: 400px)": "1fr" }, gap: "14px" },
  fieldset: { border: 0, padding: 0, margin: 0, minWidth: 0 },
  legend: { marginBottom: "10px", fontSize: "12px", fontWeight: 600 },
  themes: { display: "grid", gridTemplateColumns: { default: "repeat(3, 1fr)", "@media (max-width: 400px)": "repeat(2, 1fr)" }, gap: "8px" },
  theme: { display: "flex", alignItems: "center", justifyContent: "start", gap: "7px", padding: "11px 9px", border: `1px solid ${colorVars["--color-border"]}`, borderRadius: "10px", backgroundColor: colorVars["--color-background-card"], color: colorVars["--color-text-primary"], fontSize: "11px", cursor: "pointer", ":focus-visible": { outline: `2px solid ${colorVars["--color-accent"]}`, outlineOffset: "2px" }, ":hover": { backgroundColor: `color-mix(in srgb, ${colorVars["--color-accent"]} 8%, ${colorVars["--color-background-card"]})` } },
  swatch: (color: string) => ({ width: "14px", height: "14px", flexShrink: 0, borderRadius: "50%", backgroundColor: color }),
  selected: { borderColor: colorVars["--color-accent"], backgroundColor: `color-mix(in srgb, ${colorVars["--color-accent"]} 10%, ${colorVars["--color-background-card"]})` },
  note: { display: "flex", alignItems: "start", gap: "8px", color: colorVars["--color-text-secondary"], fontSize: "11px", lineHeight: 1.6, margin: "4px 0 0" },
  choices: { display: "grid", gap: "12px" },
  choice: { display: "flex", alignItems: "center", textAlign: "start", gap: "12px", width: "100%", padding: "16px", color: colorVars["--color-text-primary"], backgroundColor: colorVars["--color-background-card"], border: `1px solid ${colorVars["--color-border"]}`, borderRadius: "14px", cursor: "pointer", fontSize: "13px", ":focus-visible": { outline: `2px solid ${colorVars["--color-accent"]}`, outlineOffset: "2px" }, ":hover": { borderColor: colorVars["--color-accent"] } },
  choiceText: { flex: 1, minWidth: 0 },
  radio: { display: "grid", placeItems: "center", width: "19px", height: "19px", border: `1px solid ${colorVars["--color-border"]}`, borderRadius: "50%", flexShrink: 0 },
  radioSelected: { borderColor: colorVars["--color-accent"], backgroundColor: `color-mix(in srgb, ${colorVars["--color-accent"]} 15%, ${colorVars["--color-background-card"]})`, color: colorVars["--color-accent"] },
  summary: { display: "flex", alignItems: "center", gap: "14px", padding: "22px", border: `1px solid ${colorVars["--color-border"]}`, borderRadius: "14px", marginBottom: "22px", fontSize: "14px" },
  nextSteps: { padding: "18px 0", fontSize: "13px" },
  error: { color: colorVars["--color-error"], fontSize: "13px" },
  footer: { display: "flex", alignItems: "center", justifyContent: "space-between", gap: "12px", flexShrink: 0, borderTop: `1px solid ${colorVars["--color-border"]}`, padding: { default: "20px 32px", "@media (max-width: 500px)": "16px" } },
  footerHint: { fontSize: "11px", color: colorVars["--color-text-secondary"], maxWidth: "130px", lineHeight: 1.5 },
});
